CREATE USER "DB_OWNER" PASSWORD 'DB_OWNER';
CREATE USER "DB_USER" PASSWORD 'DB_USER';

CREATE TABLESPACE TS_INDEX
    OWNER "DB_OWNER"
    LOCATION '/var/lib/postgresql/TS_INDEX';
CREATE TABLESPACE TS_DATA
    OWNER "DB_OWNER"
    LOCATION '/var/lib/postgresql/TS_DATA';

GRANT ALL PRIVILEGES ON DATABASE postgres TO "DB_USER";
GRANT ALL PRIVILEGES ON DATABASE postgres TO "DB_OWNER";