CREATE TABLESPACE "TS_INDEX"
    LOCATION '/var/lib/postgresql/';
CREATE TABLESPACE "TS_DATA"
    LOCATION '/var/lib/postgresql/';


CREATE USER DB_USER PASSWORD 'DB_USER';
CREATE USER DB_USER PASSWORD 'DB_USER';

GRANT ALL PRIVILEGES ON DATABASE postgres TO DB_USER;
GRANT ALL PRIVILEGES ON DATABASE postgres TO DB_OWNER;