version: '3.3'
services:
  mq:
    container_name: mq-unipol
    image: dkr-registry.tasgroup.it/supportwas/activemq5:5.15.14
    ports:
      - 8161:8162

  database:
    container_name: postgres-unipol
    build:
      context: .
      dockerfile: ./database/Dockerfile
    image: local/netgat/anagrafiche/postgres-unipol
    environment:
      - POSTGRES_PASSWORD=docker
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  liquibase:
#    stdin_open: true
#    tty: true
#    entrypoint: /bin/sh
    build:
      context: .
      dockerfile: ./liquibase/Dockerfile
    image: local/netgat/message-repair/liquibase-unicredit
    environment:
      - CLASSPATH=liquibase/changelog
      - CONNECTION_STRING_OWNER=jdbc:postgresql://database:5432/postgres
      - CHANGE_LOG_DDL_OWNER=master_changelog_owner.xml
#      - CHANGE_LOG_DDL_USER=/liquibase/changelog/master_changelog_user.xml
      - DB_OWNER_USERNAME=DB_OWNER
      - DB_OWNER_PASSWORD=DB_OWNER
#      - CONNECTION_STRING_USER=offline:postgresql?outputLiquibaseSql=true&changeLogFile=changelog.csv
      - DB_USER_USERNAME=DB_USER
      - DB_USER_PASSWORD=DB_USER
      - DATA_TABLE_SPACE=TS_DATA
      - INDEX_TABLE_SPACE=TS_INDEX
      - DB_OWNER=DB_OWNER
      - DB_USER=DB_USER
      - CONTEXTS=user_profiler_ROLE,DriverCommon_J0TCURRENT_REVISION,DriverCommon_J0TMQDUMPER,DriverCommon_J0TRESOURCES_ZIP,DriverCommon_J1TWORKING_PROCESS,DriverCommon_YWTWIBAP,DriverCommon_JETSTARTUP,DriverCommon_JETNETWORK_MESSAGE_SUSP,CommonMonitor_J0TDOMAIN,CommonMonitor_J0TGROU_EVID,CommonMonitor_J0TGROU_EVID_REL,CommonMonitor_J0TTOPIC,CommonMonitor_J0TTSINS,CommonMonitor_J0TTSRTS,CommonMonitor_J0TORGANIZATION,CommonMonitor_J0TTSINP,CommonMonitor_J0TTSISR,CommonMonitor_J0TTSOUS,CommonMonitor_J0TTSOUT,CommonMonitor_J0TTSSTA,CommonMonitor_J0TREQUEST_TYPE,CommonMonitor_J0TTTRSZ,CommonAdmin_J0TTEMPLATE,Anagrafiche_BANK_DIRECTORY_PLUS,Anagrafiche_BIC_DIRECTORY_PLUS,Anagrafiche_COUNTRY,Anagrafiche_CURRENCY,Anagrafiche_GPI_DIRECTORY,Anagrafiche_IBAN_DIRECTORY_PLUS,CommonAnagrafiche_CURRENCY_WEB,CommonAnagrafiche_IBAN_STRUCTURE,Anagrafiche_TIPS_DIRECTORY

#    depends_on:
#      - mq
#    healthcheck:
#      test: [ "CMD", "/healthcheck/check_database_is_ready.sh", "/healthcheck/liquibase_do_your_dirty_work_now" ]
#      interval: 10s
#      timeout: 10s
#      retries: 18
  appServer:
    container_name: wildfly-unipol
    build:
      context: ./delivery
      dockerfile: Dockerfile
    image: jboss/wildfly:14.0.1.Final
    ports:
      - 9990:9990
      - 8787:8787
      - 8081:8080
    env_file:
      - wildfly.env
    volumes:
      - ./delivery/deployments/:/opt/jboss/wildfly/standalone/deployments/

