version: '3.3'
services:
  mq:
    container_name: mq-unipol
    image: dkr-registry.tasgroup.it/supportwas/activemq5:5.15.14
    ports:
      - 8161:8162

  database:
    container_name: postgres-unipol
    build:
      context: .
      dockerfile: ./database/Dockerfile
    image: local/netgat/anagrafiche/postgres-unipol
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 1521:5432


#    depends_on:
#      - mq
#    healthcheck:
#      test: [ "CMD", "/healthcheck/check_database_is_ready.sh", "/healthcheck/liquibase_do_your_dirty_work_now" ]
#      interval: 10s
#      timeout: 10s
#      retries: 18
#  appServer:
#    container_name: wildfly-unipol
#    build:
#      context: ./delivery
#      dockerfile: Dockerfile
#    image: jboss/wildfly:14.0.1.Final
#    ports:
#      - 9990:9990
#      - 8787:8787
#      - 8081:8080
#    env_file:
#      - jboss.env
#    volumes:
#      - ./delivery/deployments/:/opt/jboss/wildfly/standalone/deployments/

